name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        default: 'stable'

jobs:
  promote-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Artifacts in S3 and Docker Hub
        run: make -j2 promote BRANCH_NAME=${GITHUB_REF##*/}
        env:
          VERSION: ${{ github.event.inputs.version }}
          CHANNEL: ${{ github.event.inputs.channel }}
